docs: clarify the correct server run command (#810)
* Update README.md with correct server run command

Following current documentation I'm getting:
error: Failed to spawn: `server.py`
  Caused by: No such file or directory (os error 2)

* Update README.md as requested with uv

Using uv instead of python directly

---------

Co-authored-by: Scott Schreckengaust <scottschreckengaust@users.noreply.github.com>