Update README.md with correct server run command
Following current documentation I'm getting:
error: Failed to spawn: `server.py`
  Caused by: No such file or directory (os error 2)